PeerXp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('account/',include('account.urls')),
    path('ticket/',include('ticket.urls')),
]

account/urls.py
from django.urls import path
from . import views

#Code from here
app_name="account"

urlpatterns = [
    path('login/', views.LoginView.as_view(),name="login"),
    path('logout/',views.LogoutView.as_view(),name="logout"),

]

main/urls.py
from django.urls import path
from . import views


#Code from here

app_name='main'

urlpatterns = [
    path('',views.index_page,name="home"),
]

ticket/urls.py
from django.urls import path
from . import views

#Code from here
app_name ="ticket"

urlpatterns = [
    path('add-ticket',views.TicketFormView.as_view(),name='add_ticket'),    
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin, BaseUserManager

# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self,email,password=None,*args, **kwargs):
        if not email:
            raise ValueError("Email required to create user")
        email = self.normalize_email(email)
        user_obj = self.model(email=email)
        user_obj.set_password(password)
        user_obj.save(using=self.db)
        return user_obj
    
    def create_staff(self,email,password=None,*args, **kwargs):
        user_obj = self.create_user(email,password)
        user_obj.staff = True
        user_obj.save(using=self.db)
        return user_obj

    def create_superuser(self,email,password=None,*args, **kwargs):
        user_obj = self.create_user(email,password)
        user_obj.staff = True
        user_obj.admin = True
        user_obj.save(using=self.db)
        return user_obj


class UserProfile(AbstractBaseUser,PermissionsMixin):
    """This class override the djnago base user"""
    email               = models.EmailField(max_length=200,unique=True)
    name                = models.CharField(max_length=150,null=True,blank=True)
    active              = models.BooleanField(default=True)
    staff               = models.BooleanField(default=False)
    admin               = models.BooleanField(default=False)
    updated_at          = models.DateTimeField(auto_now=True)
    created_at          = models.DateTimeField(auto_now_add=True)

    objects = UserManager()
    USERNAME_FIELD ='email'
    REQUIRED_FIELDS= []

    def get_full_name(self):
        return self.name
    
    def get_short_name(self):
        return self.name

    def __str__(self):
        return self.email
    
    def has_perm(self,perm,object=None):
        return True
    
    def has_module_perms(self,app_label):
        return True

    @property
    def is_active(self):
        return self.active
    
    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin
    

ticket/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms

# Code from here

class LoginForm(forms.Form):
    email               = forms.EmailField(max_length=200,widget=forms.TextInput(attrs={'class':'form-control'}))
    password            = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))

ticket/forms.py
from django import forms


#Code from Here

DEPARTMENT_CHOICES = (
    ('PWSLab DevOps Support','PWSLab DevOps Support'),
    ('support','iSupport')

)

PRIORITY_CHOICES =(
    ('','None'),
    ('hign','High - Production System Down'),
    ('medium','Medium - System Impaired'),
    ('low','Low - General Guidance'),
)
CATEGORY_CHOICES =(
    ('','None'),
    ('other','Other'),
)
class TicketForm(forms.Form):
    department          = forms.ChoiceField(choices=DEPARTMENT_CHOICES,widget=forms.Select(attrs={'class':'form-control'}))
    category            = forms.ChoiceField(choices=CATEGORY_CHOICES,widget=forms.Select(attrs={'class':'form-control'}))
    pwsLab_url          = forms.URLField(max_length=200,widget=forms.TextInput(attrs={'class':'form-control'}))
    subject             = forms.CharField(max_length=200,widget=forms.TextInput(attrs={'class':'form-control'}))
    description         = forms.CharField(max_length=200,widget=forms.Textarea(attrs={'class':'form-control'}))
    contact_name        = forms.CharField(max_length=150,widget=forms.TextInput(attrs={'class':'form-control'}))
    email               = forms.EmailField(max_length=150,widget=forms.TextInput(attrs={'class':'form-control'}))
    phone               = forms.CharField(max_length=15,widget=forms.TextInput(attrs={'class':'form-control'}))
    priority            = forms.ChoiceField(choices=PRIORITY_CHOICES,widget=forms.Select(attrs={'class':'form-control'}))

account/views.py
from django.shortcuts import render, reverse, redirect
from django.views.generic import FormView, RedirectView
from django.contrib.auth import authenticate,login, logout
from .forms import LoginForm
from django.http import HttpResponseRedirect
from django.contrib import messages

# Create your views here.


class LoginView(FormView):
    """This Is the Login class Based View"""
    template_name = 'account/front/login.html'
    form_class = LoginForm


    def form_valid(self,form):
        data = form.cleaned_data
        user = authenticate(email=data['email'],password=data['password'])
        if user.is_active:
            login(self.request,user)
            return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Succesfully Login.')
        return reverse('main:home')

class LogoutView(RedirectView):
    pattern_name = 'account:login'
    def get(self,request,*args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

main/views.py
from django.shortcuts import render
from django.views.generic import FormView
from account.forms import LoginForm
from django.contrib.auth import authenticate,login
from django.shortcuts import reverse
from django.http import HttpResponseRedirect
import requests
from requests.auth import HTTPBasicAuth
import os


# Create your views here.

def index_page(request):
    # headers = {
    # 'orgId': '60001280952',
    # 'Authorization': '9446933330c7f886fbdf16782906a9e0',}
    # response = requests.get('https://desk.zoho.in/api/v1/tickets', headers=headers)
    # print("###########3")
    # print(response.json())
    # if response.status_code == 200:
    #     print("Code 200")
    # else:
    #     print("Code not 200")
    headers = {
    'Authorization': 'Zoho-oauthtoken 1000.3d0a155402dbb59f776fd63adb1e67c0.a41ea557a6a8d7e402690098b2056f60s',
}
    data = '{ "subCategory" : "Sub General", "cf" : { "cf_permanentaddress" : null, "cf_dateofpurchase" : null, "cf_phone" : null, "cf_numberofitems" : null, "cf_url" : null, "cf_secondaryemail" : null, "cf_severitypercentage" : "0.0", "cf_modelname" : "F3 2017" }, "productId" : "", "contactId" : "1892000000042032", "subject" : "Real Time analysis Requirement", "dueDate" : "2016-06-21T16:16:16.000Z", "departmentId" : "1892000000006907", "channel" : "Email", "description" : "Hai This is Description", "language" : "English", "priority" : "High", "classification" : "", "assigneeId" : "1892000000056007", "phone" : "1 888 900 9646", "category" : "general", "email" : "carol@zylker.com", "status" : "Open" }'
    response = requests.post('https://desk.zoho.com/api/v1/tickets', headers=headers, data=data)
    print("###########3")
    print(response.json())
    if response.status_code == 200:
        print("Code 200")
    else:
        print("Code not 200")
    return render(request,'main/front/index.html',{})



    
    

ticket/views.py
from django.shortcuts import render
from . import forms
from django.views.generic import FormView
from django.contrib import messages
from django.http import HttpRequest, HttpResponseRedirect
import requests

# Create your views here.


class TicketFormView(FormView):
    template_name = 'ticket/ticket.html'
    form_class = forms.TicketForm

    def get_success_url(self):
        messages.success(self.request,'Your Ticket is successfully Rised')
        return HttpResponseRedirect('add_ticket')

    def form_valid(self,form):
        data = form.cleaned_data
        print(data)
        return super().form_valid(form)

main/templates/main/front/base.html
<!doctype html>
<html lang="en">
{% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.css' %}">

    <title>Hello, world!</title>
  </head>
  <body style="background: #e0e0e0;">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #2248d4;">
        <a class="navbar-brand" href="{% url 'main:home' %}">PeerXP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ticket:add_ticket' %}">My Area</a>
            </li>
             <li class="nav-item">
                <a class="nav-link" href="#">Knowledge Base</a>
            </li>
            <li class="nav-item">
                {% if request.user.is_authenticated%}
                <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
                {% else %}
                <a class="nav-link" href="{% url 'account:login' %}">Sign In</a>
                {% endif %}
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Sign Up</a>
            </li>
            {% comment %} <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
             {% endcomment %}
            </ul>
            {% comment %} <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form> {% endcomment %}
        </div>
    </nav>
    </header>
    {% block MainContent %}
    {% endblock MainContent %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/front/index.html
{% extends 'main/front/base.html' %}
{% load static %}
{% block MainContent %}
<div>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</div>
<section style="padding: 4% 0% 1%;">
    <div class="row" >
        <div class="container">
            <div class="card">
                <div class="card-body">
                   <h3 style="text-align:center">Welcome to Zogo Tickect Api</h3>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock MainContent %}

ticket/templates/ticket/ticket.html
{% extends 'main/front/base.html' %}
{% load static %}

{% block MainContent %}
<section>
    <div class="row">
        <div class="container" style="margin-top: 5%;margin-bottom: 5%;">
            <div class="row">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-body">
                            <br>
                            <h3>Submit a ticket</h3>
                            <br>
                            <h6>Ticket Information</h6>
                            <br>
                            <div>
                                <form method="POST">
                                    {% csrf_token %}
                                    {% if messages %}
                                    <ul class="messages">
                                        {% for message in messages %}
                                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                        {% endfor %}
                                    </ul>
                                    {% endif %}
                                    <div class="form-group">
                                        <label>Department</label>
                                        {{form.department}}
                                        <small  class="form-text text-muted">{{form.department.errors}}</small>
                                    </div>
                                    <div class="form-group">
                                        <label>Category</label>
                                        {{form.category}}
                                        <small  class="form-text text-muted">{{form.category.errors}}</small>
                                    </div>
                                    <div class="form-group">
                                        <label>PWSLab Project URL</label>
                                        {{form.pwsLab_url}}
                                        <small  class="form-text text-muted">{{form.pwsLab.errors}}</small>
                                    </div>
                                    <div class="form-group">
                                        <label>Subject</label>
                                        {{form.subject}}
                                        <small  class="form-text text-muted">{{form.subject.errors}}</small>
                                    </div>
                                     <div class="form-group">
                                        <label>Description</label>
                                        {{form.description}}
                                        <small  class="form-text text-muted">{{form.description.errors}}</small>
                                    </div>
                                    <br>
                                    <h6>Contact Details</h6>
                                    <br>
                                     <div class="form-group">
                                        <label>Contact Name</label>
                                        {{form.contact_name}}
                                        <small  class="form-text text-muted">{{form.contact_name.errors}}</small>
                                    </div>
                                    <div class="form-group">
                                        <label>Email</label>
                                        {{form.email}}
                                        <small  class="form-text text-muted">{{form.email.errors}}</small>
                                    </div>
                                    <div class="form-group">
                                        <label>Phone No</label>
                                        {{form.phone}}
                                        <small  class="form-text text-muted">{{form.phone.errors}}</small>
                                    </div>
                                    <br>
                                    <h6>Additional Information</h6>
                                    <br>
                                    <div class="form-group">
                                        <label>Priority</label>
                                        {{form.priority}}
                                        <small  class="form-text text-muted">{{form.priority.errors}}</small>
                                    </div>
                                    {% comment %} <div class="form-group">
                                        <label>Attach a file(Up to 20 MB )</label>
                                        {{form.file_upload}}
                                        <small  class="form-text text-muted">{{form.file_upload.errors}}</small>
                                    </div> {% endcomment %}
                                    <br>
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <h5 style="text-align:center">Popular Articles</h5>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock MainContent %}